'use client';
import {useEffect,useState} from 'react';import type {Post} from '../../db/posts';
const blank={id:'',title:'',summary:'',content:'',category:'Qualidade do leite',author:'Equipe LabITec POA',status:'draft'};
export default function Editor(){const [posts,setPosts]=useState<Post[]>([]),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false);
async function load(){try{const r=await fetch('/api/posts');const b=await r.json() as Post[] & {error?:string};if(!r.ok)throw Error(b.error);setPosts(b);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.')}finally{setLoading(false)}}
useEffect(()=>{load()},[]);useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
function change(k:string,v:string){setForm(p=>({...p,[k]:v}));setDirty(true);setMessage('')}
function choose(p:typeof blank){if(dirty&&!confirm('Descartar as alterações ainda não salvas?'))return;setForm(p);setDirty(false);setMessage('');document.getElementById('editor-title')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json() as {id:string;error?:string};if(!r.ok)throw Error(b.error);setForm(p=>({...p,id:b.id}));setDirty(false);await load();setMessage(form.status==='published'?'Matéria publicada com sucesso.':'Rascunho salvo com sucesso.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}}
return <div className="editor-layout"><aside className="posts-panel"><div className="panel-top"><h2>Matérias ({posts.length})</h2><button className="button small" onClick={()=>choose({...blank})}>Nova matéria</button></div>{loading&&<p>Carregando matérias…</p>}{posts.map(p=><button className={'post-item '+(form.id===p.id?'selected':'')} key={p.id} onClick={()=>choose({id:p.id,title:p.title,summary:p.summary,content:p.content,category:p.category,author:p.author,status:p.status})}><span className={'status '+p.status}>{p.status==='published'?'Publicada':'Rascunho'}</span><strong>{p.title}</strong><small>{p.author}</small></button>)}{!loading&&!posts.length&&<p>Crie sua primeira matéria.</p>}<button className="retry" onClick={load}>Atualizar lista</button></aside><form onSubmit={save} className="editor-form"><div className="eyebrow">EDITOR DO BLOG</div><h2 id="editor-title">{form.id?'Editar matéria':'Nova matéria'}</h2><p>Salve como rascunho ou publique para aparecer no blog.</p><label>Título<input required maxLength={180} value={form.title} onChange={e=>change('title',e.target.value)} placeholder="Qual assunto vamos compartilhar?"/></label><label>Resumo<textarea required maxLength={500} rows={3} value={form.summary} onChange={e=>change('summary',e.target.value)} placeholder="Uma breve apresentação da matéria"/></label><div className="form-row"><label>Categoria<select value={form.category} onChange={e=>change('category',e.target.value)}>{['Qualidade do leite','Pesquisa e inovação','No laboratório','Campo e produção'].map(x=><option key={x}>{x}</option>)}</select></label><label>Autor<input required maxLength={120} value={form.author} onChange={e=>change('author',e.target.value)}/></label></div><label>Conteúdo<textarea required maxLength={100000} rows={14} value={form.content} onChange={e=>change('content',e.target.value)} placeholder="Escreva a matéria. Separe os parágrafos com uma linha em branco."/></label><label>Visibilidade<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="draft">Rascunho — somente no painel</option><option value="published">Publicada — visível no blog</option></select></label>{message&&<div role="status" className="success">{message}</div>}{error&&<div role="alert" className="error">{error}</div>}<div className="save-row"><button className="button" disabled={busy}>{busy?'Salvando…':form.status==='published'?'Salvar e publicar':'Salvar rascunho'}</button>{form.id&&form.status==='published'&&<a href={'/materias/'+form.id} target="_blank" rel="noreferrer">Ver no blog</a>}<small>{dirty?'Alterações não salvas':'Tudo em dia'}</small></div></form></div>}
